### ISSUE TITLE
Introduce GitHub workflow to deny PR to main from non integration branches

### ISSUE THREAD

**Issue by stan-konnov** [stan-konnov/apollo#9]
```
name: Check pull request source branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited
jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        run: |
          if [ ${{ github.head_ref }} != "dev" ] && [ ${{ github.base_ref }} == "main" ]; then
            echo "Merge requests to main branch are only allowed from dev branch."
            exit 1
          fi
```

Check how to deny PRs to stage from non-dev.
